retail_sales:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DB_HOST', 'db') }}"
      port: "{{ env_var('DB_PORT', '5432') | int }}"
      dbname: "{{ env_var('DB_NAME', 'retail') }}"
      user: "{{ env_var('DB_USER', 'retail') }}"
      password: "{{ env_var('DB_PASS', 'retail_pass') }}"
      schema: marts
      threads: 4
      sslmode: "{{ env_var('DB_SSLMODE', 'require') }}"
